version: "3.2"
services:
  user-registration-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=registration
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registration
    ports:
      - "5432:5432"
    restart: unless-stopped

